(function () {
  const roles = ['Everyone', 'Home manager', 'Parent', 'Child', 'Student', 'Caregiver', 'Elder'];
  const group = (intent, role, ...texts) => texts.map(text => [role, text, intent]);

  const sets = [
    { id: 'purpose', label: 'Purpose & first use', icon: 'compass', route: 'global/overview', items: [
      ...group('purpose', 'Everyone',
        'What is Home Manager for?',
        'What family problem does this app solve?',
        'Why should our family use one shared home app?',
        'Is this a planner, a record book or both?',
        'What can I manage from one place?',
        'How does this make family life less stressful?'),
      ...group('today', 'Home manager',
        'What should I look at first every morning?',
        'How do I know what needs attention now?',
        'Where can I see the whole family day at a glance?',
        'Can I see tasks, events, supplies and bills together?',
        'How do I find the next important family action?',
        'What does the Today page tell me?'),
      ...group('audience', 'Parent',
        'Who in the family is this app designed for?',
        'Can both parents use the same family structure?',
        'Can a household manager run daily work here?',
        'Can children understand their responsibilities?',
        'Can students manage schoolwork here?',
        'Can caregivers and elders find relevant information?'),
      ...group('start', 'Everyone',
        'Where should a new family start?',
        'What should I set up before adding daily work?',
        'What are the minimum details needed to begin?',
        'Can I explore the app before entering real information?',
        'Which page helps me understand the app quickly?',
        'How do I return to the starting point?'),
      ...group('daily-settings', 'Home manager',
        'What belongs in the daily sections?',
        'What belongs in Settings?',
        'Where should permanent household information go?',
        'Where should changing tasks and plans go?',
        'Why are profiles and recurring facts separated from daily work?',
        'How do stable records create useful reminders?'),
      ...group('scope', 'Everyone',
        'Which parts of Indian family life are covered?',
        'Can this replace separate chore, calendar and shopping lists?',
        'Does it include money, health, study and community life?',
        'Can it help during a household emergency?',
        'Does it keep family records as well as plans?',
        'Where can I check whether a feature exists?')
    ]},
    { id: 'navigation', label: 'Finding your way', icon: 'signpost', route: 'global/overview', items: [
      ...group('persona-reset', 'Everyone',
        'How does top bar profile switching reset the sidebar to Mom (Food), Father (Finance), Kids (Education) or Family (All)?',
        'How do 3-level proficiency tracks (Level 1: Learning, Level 2: Revision, Level 3: Expert) clarify study progress?'),
      ...group('sidebar', 'Everyone',
        'What do the seven sidebar groups mean?',
        'How do I switch between Household, Family and Money?',
        'Where are Care, Learning and Community?',
        'How do I return to Today from another section?',
        'Which navigation is used for daily family work?',
        'Can I collapse the sidebar when I need more space?'),
      ...group('section-tabs', 'Everyone',
        'What do the tabs below the page title do?',
        'How do I move between pages inside one family area?',
        'Where are tasks after I choose Household?',
        'Where are bills after I choose Money?',
        'Where are health and emergency pages?',
        'Why do the section tabs change with the sidebar group?'),
      ...group('search', 'Everyone',
        'How do I search the whole app?',
        'Can I search by a task or family member name?',
        'Can search take me directly to the correct section?',
        'Where do app-help answers appear in search?',
        'What should I do when search finds nothing?',
        'Does search look through every household record?'),
      ...group('today', 'Home manager',
        'Where can I see overdue work?',
        'Where can I see the next seven days?',
        'How do I filter Today by family member?',
        'Where can I check low-stock items quickly?',
        'Where is this month\'s spending total?',
        'How do I open an item shown on Today?'),
      ...group('settings', 'Parent',
        'How do I open Settings?',
        'Why does Settings have seven groups?',
        'Where do I edit the household profile?',
        'Where do I manage people and roles?',
        'Where are home services and permanent records configured?',
        'How do I leave Settings and return to daily work?'),
      ...group('mobile', 'Everyone',
        'How do I open navigation on a phone?',
        'Which pages are always available in the mobile bar?',
        'How do I reach the other sections on mobile?',
        'Can I use search from a small screen?',
        'Can I add something without opening the sidebar?',
        'Will tables and calendars remain usable on mobile?')
    ]},
    { id: 'actions', label: 'Adding & updating', icon: 'square-pen', route: 'global/overview', items: [
      ...group('quick-add', 'Everyone',
        'How do I add something quickly?',
        'What can the Add button create?',
        'Can I add a task from any page?',
        'Can I add an event without opening the calendar first?',
        'Where should I record an expense?',
        'How do I close the Add panel without saving?'),
      ...group('tasks', 'Home manager',
        'How do I create a household task?',
        'Can I assign a task to a family member?',
        'Can I set a due date and priority?',
        'Can a task repeat daily, weekly, monthly or yearly?',
        'How do I mark a task complete?',
        'What happens when I complete a recurring task?'),
      ...group('events', 'Parent',
        'How do I add a family event?',
        'Can I record a venue and event category?',
        'Where does a new event appear?',
        'Can I browse previous and future months?',
        'Can school and community events use the same calendar?',
        'How do I get back to the current month?'),
      ...group('food', 'Home manager',
        'How do I add a shopping or pantry item?',
        'Can I record quantity and unit?',
        'How do I plan a family meal?',
        'Can I assign who will cook?',
        'Where do low-stock items appear?',
        'Can food and supplies be managed on one page?'),
      ...group('money', 'Parent',
        'How do I record a household expense?',
        'Can I categorise spending?',
        'Where can I review monthly spending?',
        'How do I record a bill or renewal date?',
        'Are bills separate from everyday expenses?',
        'Can I edit a money record after saving it?'),
      ...group('record-actions', 'Everyone',
        'How do I edit an existing record?',
        'How do I delete something entered by mistake?',
        'Can I undo an accidental deletion?',
        'How do I change an item from to-do to in progress?',
        'Where does the app confirm that my change was saved?',
        'What happens if browser storage cannot save my change?')
    ]},
    { id: 'workflows', label: 'Everyday workflows', icon: 'workflow', route: 'global/overview', items: [
      ...group('day-plan', 'Home manager',
        'How do I plan the family day?',
        'How do I see who is responsible for each task?',
        'Can I combine appointments and chores in one agenda?',
        'How do I spot work that is already late?',
        'How do I prepare tomorrow before today ends?',
        'Can I see only one person\'s responsibilities?'),
      ...group('calendar', 'Parent',
        'How do I coordinate school, work and family events?',
        'Can the calendar show household and study events?',
        'Where should birthdays and anniversaries be added?',
        'How do I record a doctor or service appointment?',
        'Can I keep a location with an event?',
        'How do I review all events in a month?'),
      ...group('home-running', 'Home manager',
        'Where do I manage chores and routines?',
        'How do I track repairs and maintenance?',
        'Where do I record appliance or property information?',
        'How do I manage vehicles and service dates?',
        'Where is domestic-help information kept?',
        'Can sustainability goals be tracked?'),
      ...group('money-workflow', 'Parent',
        'How do I understand where household money went?',
        'Where do I track bills that are coming due?',
        'How do I keep insurance renewal dates visible?',
        'Where are tax dates and subscriptions?',
        'Can upcoming financial dates appear on Today?',
        'How do I separate a payment from a permanent policy record?'),
      ...group('learning', 'Student',
        'Where is the Peepal parent portal?',
        'Where do I enter the confirmed school timetable?',
        'How do I track attendance without inventing school data?',
        'Where does a student complete daily self-assessment?',
        'How do we record Student-Parent-Tutor actions?',
        'Where do clubs, sports and co-curricular growth belong?'),
      ...group('community', 'Everyone',
        'What is the Community area for?',
        'Where can I save neighbourhood updates?',
        'How do I track a civic issue?',
        'Where can I keep local service contacts?',
        'Can I plan volunteering and community events?',
        'Are community polls shared online?')
    ]},
    { id: 'family', label: 'People, care & safety', icon: 'users-round', route: 'home/family', items: [
      ...group('people', 'Everyone',
        'Where can I see everyone in the household?',
        'How do I add a family member?',
        'Can each person have a family role?',
        'Where can I edit a person\'s profile?',
        'How is family wellbeing shown?',
        'Is wellbeing meant to rank family members?'),
      ...group('responsibility', 'Parent',
        'How do we make responsibilities clear?',
        'Can a task be left unassigned?',
        'How do I check one child\'s tasks?',
        'Where can I see how work is distributed?',
        'Can family members share a common calendar?',
        'How do I hand a task to another person?'),
      ...group('care', 'Caregiver',
        'Where should caregiver instructions be recorded?',
        'How do I track a health appointment?',
        'Where do I keep a masked doctor reference?',
        'Can medicine planning be kept with health records?',
        'How do I make care dates visible on Today?',
        'Where do I review health and safety setup?'),
      ...group('student-role', 'Child',
        'Where can a child see today\'s chores?',
        'Can a child mark an assigned task complete?',
        'Where can a student see homework?',
        'Can a student use the focus timer?',
        'How can a child find emergency help?',
        'Can children avoid seeing unnecessary financial details?'),
      ...group('elder-role', 'Elder',
        'Can an elder find emergency numbers quickly?',
        'Where is the household emergency card?',
        'Can the interface use stronger contrast?',
        'Can the app be used with keyboard navigation?',
        'Where can an elder find caregiver information?',
        'Can important dates appear without opening many pages?'),
      ...group('emergency', 'Everyone',
        'How do I open emergency help immediately?',
        'Which Indian emergency numbers are included?',
        'Does Home Manager call emergency services for me?',
        'Where do I add the home address for emergencies?',
        'Where do I keep trusted emergency contacts?',
        'What information should be prepared before an emergency?')
    ]},
    { id: 'privacy', label: 'Privacy, data & recovery', icon: 'shield-check', route: 'settings/app', items: [
      ...group('local-data', 'Parent',
        'Where is my family data stored?',
        'Is household data uploaded to a server?',
        'Does the app require an account?',
        'Can another device see these records automatically?',
        'Does clearing browser data remove the household?',
        'Is browser storage encrypted?'),
      ...group('sensitive-data', 'Everyone',
        'Should I store full Aadhaar or PAN numbers here?',
        'Should I save passwords, PINs or bank credentials?',
        'Can I upload medical scans safely?',
        'What kind of document reference is appropriate?',
        'How should I record an account number?',
        'Where should official documents be kept?'),
      ...group('backup', 'Home manager',
        'How do I back up the whole household?',
        'What information is included in an export?',
        'Where should I keep the exported file?',
        'How often should the family make a backup?',
        'Can I move data to another browser?',
        'How do I know an export was created?'),
      ...group('restore', 'Parent',
        'How do I restore a household backup?',
        'Will import replace the current household?',
        'Does the app validate an imported file?',
        'What should I do before importing data?',
        'Can I recover data without a backup?',
        'How do I reset the demonstration data?'),
      ...group('limitations', 'Everyone',
        'Does the app send background reminders?',
        'Does it synchronise family changes in real time?',
        'Can it connect directly to banks or UPI?',
        'Does it track family members\' live location?',
        'Can it submit government or municipal forms?',
        'Does it provide medical or financial advice?'),
      ...group('data-control', 'Home manager',
        'How do I control what stays in the app?',
        'Can I delete individual records?',
        'Can I export before removing information?',
        'What happens when I reset the app?',
        'Where can I read the privacy boundaries?')
    ]},
    { id: 'confidence', label: 'Confidence & accessibility', icon: 'badge-check', route: 'global/questions', items: [
      ...group('help', 'Everyone',
        'Where can I get help using the app?',
        'Can I ask a question in everyday language?',
        'How do I browse help without knowing a search term?',
        'Can I filter help for my family role?',
        'Can I see which product areas have been checked?',
        'How do I open the correct page from a help answer?'),
      ...group('empty-states', 'Everyone',
        'What should I do when a page is empty?',
        'Does an empty page offer the correct next action?',
        'How do I know which information is required?',
        'Can I cancel a form without entering anything?',
        'Will unsaved form data change my records?',
        'How do I recognise a successful save?'),
      ...group('feedback', 'Everyone',
        'How does the app show overdue or urgent work?',
        'How are low-stock items highlighted?',
        'Where do renewal and due-date signals appear?',
        'How do I know a task is complete?',
        'What happens after deleting a record?',
        'Does the app warn me when saving fails?'),
      ...group('accessibility', 'Elder',
        'Can I use the app without a mouse?',
        'Is there a skip link for keyboard users?',
        'Do icon buttons have accessible names?',
        'Does focus move into dialogs when they open?',
        'Can dialogs be closed with Escape?',
        'Can an elder choose a comfortable light background?'),
      ...group('responsive', 'Everyone',
        'Can the app be used on a phone?',
        'Does navigation remain available on small screens?',
        'Will long labels fit without overlapping?',
        'Can wide tables be read on mobile?',
        'Does the Add panel fit the full phone height?',
        'Can emergency help be opened on mobile?'),
      ...group('boundaries', 'Everyone',
        'Is every visible feature actually working?',
        'Which features depend on external official services?',
        'How can I tell local notes from connected online data?',
        'Does the app clearly state what it cannot do?',
        'Where can I verify the app\'s intended purpose?')
    ]}
  ];

  const answers = {
    purpose: ['One family operating space', 'Home Manager combines the family agenda, household work, money, care, learning, community plans and stable records in one local-first app.', 'global/overview', 'direct'],
    today: ['Start with Today', 'Today combines urgent tasks, upcoming events, low stock, monthly spending and due records. Select a family member to narrow the agenda.', 'global/overview', 'direct'],
    audience: ['Seven family perspectives are supported', 'The same household structure serves home managers, parents, children, students, caregivers and elders. Responsibility and relevance come from assigned records and focused sections.', 'home/family', 'direct'],
    start: ['Set up the family, then run the day', 'Begin in Settings with the household profile and people. Return to Today for the first task or event; enter spending and commitments inside their owning family section.', 'settings/household', 'settings'],
    'daily-settings': ['Changing work stays outside Settings', 'Tasks, events, shopping, section budgets, spending and follow-ups belong in the seven daily groups. Profiles, addresses, sync consent and other stable facts belong in Settings.', 'settings/household', 'settings'],
    scope: ['Seven areas cover the household', 'Today, Household, Family, Money, Care, Learning and Community cover the operating scope. Help & Guide checks purpose and usability across all seven.', 'global/questions', 'direct'],
    sidebar: ['Use the left sidebar for the seven life areas', 'Choose one area in the sidebar. Today is the family command centre; the other six group related daily and weekly work. Collapse it with the panel control.', 'global/overview', 'direct'],
    'section-tabs': ['Expand a life area in the sidebar', 'Select a coloured sidebar group to expand its related pages beneath it. Each group contains no more than seven choices.', 'home/overview', 'direct'],
    search: ['Search records and app guidance together', 'Open Search in the header and type a record name or a plain-language product question. Results are capped at seven and open the relevant destination.', 'global/questions', 'direct'],
    settings: ['Settings holds stable household facts', 'Open Settings at the bottom of the sidebar. Its three focused pages cover household identity, people and roles, and app data, privacy and connections.', 'settings/household', 'settings'],
    mobile: ['Use the bottom bar and menu on mobile', 'Today, Calendar, Tasks and Food stay in the bottom bar. More opens the sidebar; Search and Add remain in the header.', 'global/overview', 'direct'],
    'quick-add': ['Use Add for common non-financial capture', 'The header Add button opens seven common tasks, events and household records. Financial entries stay in their owning section. Close the drawer with Cancel, X or Escape.', 'global/overview', 'workflow'],
    tasks: ['Create and assign a task', 'Open Household > Tasks & routines or use Add > Task. Set the owner, date, priority and repeat rule; completing a recurring task advances its due date.', 'home/tasks', 'workflow', { kind: 'task', context: 'home' }],
    events: ['Use the shared family calendar', 'Open Family > Calendar or use Add > Calendar event. Events carry a date, category and venue and appear in the month view and Today agenda.', 'home/calendar', 'workflow', { kind: 'event', context: 'home' }],
    food: ['Manage meals and supplies together', 'Open Household > Food & supplies. Add pantry quantities or plan a dated meal with an assigned cook; low stock is surfaced on Today.', 'home/inventory', 'workflow', { kind: 'inventory', context: 'home' }],
    money: ['Enter locally, report centrally', 'Record an expense, budget or commitment in the section that caused it: vehicle costs in Vehicles, health costs and cover in Health, groceries in Food, school fees in Learning, and home costs in Property. Money is a read-only consolidation hub.', 'home/finance', 'workflow'],
    'record-actions': ['Use the row actions and save feedback', 'Edit and Delete controls appear with supported records. Saving shows a confirmation toast; deletion offers Undo. A storage failure produces a backup warning.', 'global/overview', 'workflow'],
    'day-plan': ['Build the plan with assigned tasks and events', 'Today sorts the next seven actionable items by date and can filter them by family member. Add or update work in its owning section.', 'global/overview', 'workflow'],
    calendar: ['One calendar coordinates family time', 'Family > Calendar combines home, study and community events. Use the month controls to browse, Today to return, and Add event to capture a plan.', 'home/calendar', 'workflow', { kind: 'event', context: 'home' }],
    'home-running': ['Household contains recurring home operations', 'Tasks & routines, Food & supplies, Property & repairs, Vehicles, Domestic help and Sustainability sit together under Household.', 'home/overview', 'workflow'],
    'money-workflow': ['Money consolidates seven family areas', 'Budget, Cash flow, Spending, Commitments, Net worth and Reports summarise source-owned records. Open Source from a report to add or correct the vehicle, health, food, property, learning, family or community record.', 'home/finance', 'workflow'],
    learning: ['One Peepal and CBSE suite from Class 6 to 12', 'Dashboard opens the verified Peepal hub and parent portal. Curriculum includes outcomes and daily self-assessment; Planner owns home study, confirmed school timetable and school dates; Assignments and Assessments hold school work and marks; Practice holds questions and errors; Reports combines readiness, attendance, Tutor actions and co-curricular growth.', 'study/overview', 'workflow'],
    community: ['Community is a local personal organiser', 'Save neighbourhood updates, events, volunteer plans, civic follow-ups, service contacts and guides. These records stay in this browser and are not public posts.', 'community/overview', 'workflow'],
    people: ['Profiles define the household', 'Settings > People & roles manages stable profiles. Family > Family pulse shows the current household and wellbeing without treating it as a score or competition.', 'settings/people', 'settings'],
    responsibility: ['Assign work by name', 'Tasks can be assigned or left unassigned. Today shows each person\'s workload and the family filter isolates one member\'s agenda.', 'home/tasks', 'workflow', { kind: 'task', context: 'home' }],
    care: ['Use the care register that owns the action', 'Care has separate Health, Medicines, Appointments, Elder care, Emergency and Pets registers. Their due dates roll up to the Care overview and Today. Store only masked references.', 'home/care', 'workflow'],
    'student-role': ['Each child gets a separate Peepal and CBSE workspace', 'Select the child in Learning. Class 7 follows the Peepal secondary model with competency, language, self-assessment and school work; Class 12 uses the published PCM plus Computer Science subject group and adds board-pattern practice, projects and separate practical or internal marks. Reports never compare siblings.', 'study/overview', 'boundary'],
    'elder-role': ['Key information stays close to the surface', 'Emergency is always on the right utility rail, due dates appear on Today, and the background control is beside the local profile. Standard keyboard navigation is supported.', 'home/life/emergency', 'direct'],
    emergency: ['Emergency help is one action away', 'The Emergency button shows Indian helplines and the household card. Configure the address in Household profile and trusted information in Care > Emergency. The app does not dispatch help.', 'home/life/emergency', 'workflow'],
    'local-data': ['Household records stay in this browser profile', 'Google and SMS imports become local review suggestions; Google access tokens exist only in memory and SMS backup files are parsed without upload. Local records can be removed by clearing site data, and localStorage is not encrypted.', 'settings/app', 'privacy'],
    'sensitive-data': ['Store references, never secrets', 'Do not enter full identity numbers, passwords, PINs, credentials or scans. Use masked hints here and keep official documents in trusted official or encrypted services.', 'settings/app', 'privacy'],
    backup: ['Export a JSON backup deliberately', 'Settings > App & data exports the complete local household. Store that file securely and repeat backups after meaningful changes.', 'settings/app', 'settings'],
    restore: ['Import only a trusted backup', 'Settings > App & data validates the JSON structure before replacing current data. Export the current household first. Without a backup, cleared browser data cannot be recovered.', 'settings/app', 'settings'],
    limitations: ['This static app has explicit boundaries', 'It has no direct bank feeds, live location or professional advice. Calendar and Gmail use session-only Google browser authorization; phone SMS works through local backup import because a website cannot read the live Android inbox.', 'settings/app', 'boundary'],
    'data-control': ['You control local records and backups', 'Edit or delete individual records, export before major changes, and use Reset only when you intend to restore demonstration data.', 'settings/app', 'privacy'],
    help: ['Help & Guide audits the product itself', 'Browse seven usability areas, filter by family role, or search in everyday language. Every answer names the purpose and opens its actual destination.', 'global/questions', 'direct'],
    'empty-states': ['Empty pages provide a next action', 'Supported empty views show an Add action. Drawers identify required fields and can be dismissed without saving through Cancel, X or Escape.', 'global/overview', 'direct'],
    feedback: ['Status is visible at the point of work', 'Today and notifications surface overdue, due and low-stock signals. Completion updates the record; save, delete, undo and failure feedback appear as toasts.', 'global/overview', 'direct'],
    accessibility: ['Core navigation follows browser standards', 'The app includes a skip link, labelled icon buttons, keyboard-focusable controls, native dialogs with Escape support and twelve named light backgrounds that preserve readable text contrast.', 'global/questions', 'direct'],
    responsive: ['The core experience adapts to small screens', 'Mobile navigation, search, Add, emergency help, drawers and alternative calendar layouts remain available without depending on desktop hover.', 'global/overview', 'direct'],
    boundaries: ['Local and external capabilities are labelled', 'Community content is identified as local, emergency links are external, and unsupported sync, notification, financial, medical and government integrations are stated rather than simulated.', 'settings/app', 'boundary']
  };

  const questions = sets.flatMap(set => set.items.map((item, index) => ({
    id: `${set.id}-${index + 1}`,
    category: set.id,
    categoryLabel: set.label,
    icon: set.icon,
    defaultRoute: set.route,
    role: item[0],
    text: item[1],
    intent: item[2]
  })));

  function answer(question) {
    const item = answers[question.intent] || answers.help;
    return {
      headline: item[0],
      detail: item[1],
      route: item[2] || question.defaultRoute,
      status: item[3] || 'direct',
      capture: item[4] || null
    };
  }

  function search(query = '', category = 'all', role = 'all') {
    const terms = String(query).toLowerCase().trim().split(/\s+/).filter(Boolean);
    return questions
      .filter(question => (category === 'all' || question.category === category) && (role === 'all' || question.role === role || question.role === 'Everyone'))
      .map(question => {
        const answerText = answers[question.intent]?.slice(0, 2).join(' ') || '';
        const haystack = `${question.text} ${question.categoryLabel} ${question.role} ${answerText}`.toLowerCase();
        const score = terms.reduce((total, term) => total + (haystack.includes(term) ? 1 : 0), 0);
        return { question, score };
      })
      .filter(item => !terms.length || item.score > 0)
      .sort((a, b) => b.score - a.score || a.question.id.localeCompare(b.question.id))
      .slice(0, 7)
      .map(item => item.question);
  }

  window.HM = window.HM || {};
  window.HM.questions = { roles, sets, questions, answers, answer, search };
})();
