(function () {
  window.HM = window.HM || {};
  const root = window.HM.chapterSummaries = window.HM.chapterSummaries || {};
  const school = root.school = root.school || {};

  const norm = value => value.toLowerCase().replace(/[^a-z0-9\u0900-\u097f\u0b80-\u0bff]+/g, '-').replace(/^-|-$/g, '');
  const add = (bookId, subject, title, bigIdea, story, essentialResults, problemFlow, examTraps, rapidRecall) => {
    const value = { subject, title, bigIdea, story, essentialResults, problemFlow, examTraps, rapidRecall };
    school[`${subject}::${title}`] = value;
    root[`${subject}::${title}`] = value;
    root[`${norm(subject)}-${norm(title)}`] = value;
    root[`${bookId}::${title}`] = value;
  };

  // Poorvi — 15 individual chapters replacing the previous 5 unit-level entries
  add('g7-english', 'English', 'The Day the River Spoke',
    'A story can make the argument for equality more powerfully than a rule, when a character discovers her own courage through a voice she recognises as nature.',
    'Jahnavi walks to the river and hears it challenge the idea that a girl should stay home instead of going to school. The river is not supernatural: its voice is her own suppressed courage taking a familiar, trustworthy form. She enters the classroom and claims her place. The three texts in Unit 1 share one message: learning becomes possible when we notice an injustice, persist through it, and support others to do the same.',
    ['The river is a personification of Jahnavi\'s inner courage, not a magical event.','The barrier is social and gendered: a girl\'s education treated as less urgent than household duties.','The turning point is Jahnavi\'s own decision; she is not rescued.','The unit connects: notice → persist → support → learning is possible.'],
    ['Identify the unfair rule or barrier in the story.','Name whose voice the river represents.','Explain the decision Jahnavi makes and what changes after it.','Connect her choice to the unit idea about learning.'],
    ['Treating the river as a literal, supernatural speaker rather than a narrative device for Jahnavi\'s courage.','Calling her "brave" without explaining what specific barrier she crossed.'],
    ['River = inner voice','barrier = unequal access to school','turning point = Jahnavi enters','personification carries the argument']);

  add('g7-english', 'English', 'Try Again',
    'Perseverance is the decision to try again after failure; observing a small creature at the moment of its final success can restore a person\'s courage.',
    'The poem retells the legend of King Bruce of Scotland, who watched a spider attempt to spin its web many times before finally succeeding. Each stanza shows an attempt and the result. The spider\'s stubborn effort maps directly onto Bruce\'s situation: he too has failed repeatedly and is tempted to give up. The final success of the spider restores his will to continue fighting for his kingdom.',
    ['Each stanza shows one attempt and its outcome, building to the decisive success.','The poem uses a consistent rhyme scheme to make the moral feel rhythmically inevitable.','The analogy is explicit: small creature + perseverance = model for a king.','The moral is stated, not hidden: try again.'],
    ['Read each stanza and note what the spider does and what Bruce observes.','Identify the rhyme scheme and explain its effect.','Explain how the spider\'s experience directly models Bruce\'s situation.','State the moral in your own words with one modern example.'],
    ['Describing the spider\'s effort in detail without connecting it to Bruce\'s lesson.','Confusing the spider\'s number of attempts with the number of stanzas in the poem.'],
    ['Bruce watches spider','repeated failure → final success','spider = perseverance model','try again = the moral']);

  add('g7-english', 'English', 'Three Days to See',
    'Imagining the loss of a sense sharpens gratitude for it; Helen Keller argues that sighted people waste their most precious sense through inattention.',
    'Helen Keller, who was blind and deaf, imagines what she would do if she gained sight for exactly three days. Day one she would look at faces of loved ones and friends; day two she would go to museums, watch dawn break over the city, and see life at its most vivid; day three she would go to busy New York streets to watch ordinary people go about their lives. Her argument runs throughout: those who can see rarely look as carefully as she imagines doing in three precious days.',
    ['The essay is structured as three imagined days, each representing a different kind of value.','Keller argues by contrast: she who cannot see imagines more fully than most who can.','The essay moves from personal (faces) to historical (art) to universal (ordinary people).','Central claim: use your senses now, as if you might lose them.'],
    ['Identify what Keller would look at on each of the three days.','Explain how each day represents a different kind of seeing or value.','Locate the contrast between her imagined sight and how sighted people actually see.','State her argument in one sentence.'],
    ['Listing what Keller would see as a sightseeing itinerary and missing the philosophical argument about attention.','Making her disability the main subject instead of her argument about how everyone should live.'],
    ['Day 1: loved faces','Day 2: nature and human history','Day 3: ordinary life','message: use senses fully now']);

  add('g7-english', 'English', 'Animals, Birds, and Dr. Dolittle',
    'Listening across a barrier is a form of respect; unusual knowledge freely shared can become a great service.',
    'The parrot Polynesia reveals to Dr. Dolittle that every animal species has its own language. Dolittle\'s respectful curiosity leads him to learn these languages, transforming him from an unsuccessful people\'s doctor into a celebrated animal doctor. Polynesia acts as a bridge between two worlds. The story shows that empathy and listening—not superiority—produce the most useful service.',
    ['Polynesia is the bridge between human and animal worlds; her knowledge enables everything that follows.','Dolittle\'s willingness to listen respectfully is the source of his transformation, not any special power.','The story argues that unusual knowledge freely applied in service of others creates real skill.','Empathy means understanding another\'s experience, not just sympathising with it.'],
    ['Identify the problem Dolittle had as a people\'s doctor.','Explain what Polynesia tells him and why this information changes everything.','Describe what Dolittle does with the knowledge and what result follows.','State what the story argues about listening and service.'],
    ['Calling Dolittle simply "kind to animals" and missing that he systematically learns their languages.','Treating Polynesia as a minor character rather than the turning-point figure who changes the story.'],
    ['Polynesia bridges worlds','Dolittle listens and learns','unusual knowledge used in service','empathy creates real skill']);

  add('g7-english', 'English', 'A Funny Man',
    'Nonsense verse creates humour by systematically reversing ordinary expectations; the poem\'s comedy depends on the reader knowing exactly what the normal rule is.',
    'The poem describes a man who does everything wrong: he wears a shoe on his head and hats on his feet, hops home on his head, calls a bun a rose, and mixes all the senses. Every line turns one familiar rule upside down. The sound of the poem—its rhythm and rhyme—makes the wrongness feel gleeful and rhythmically satisfying, not confusing. The humour is not random; it is organised reversal.',
    ['Every image in the poem breaks exactly one rule of ordinary life, making the reversal clear and funny.','The poem\'s rhythm and rhyme scheme are consistent, which makes the absurdity feel controlled, not chaotic.','Nonsense verse invites readers to know the rule first, then enjoy the deliberate breaking of it.','Sound effects (onomatopoeia, alliteration) add an extra layer of playfulness to the images.'],
    ['For each image, state the normal rule and then the poem\'s reversal of it.','Identify the rhyme scheme and describe the effect of its regularity amid the chaos.','Explain what "nonsense verse" means as a literary form.','Describe the overall comic effect the poem creates through its accumulation of reversals.'],
    ['Correcting the poem\'s images as if they were mistakes rather than deliberate, organised humour.','Calling the poem "random" or "silly" without explaining the principle of organised reversal at work.'],
    ['Normal rule first','systematic reversal','rhythm stays consistent','accumulation = comic effect']);

  add('g7-english', 'English', 'Say the Right Thing',
    'Real politeness requires listening and judgement, not memorised phrases; when rehearsed courtesy meets an actual conversation, comedy and a real lesson follow.',
    'In the play, a character has rehearsed a set of polite responses and uses them regardless of what the other person actually says or needs. The result is a series of comic mismatches. The audience sees that tact requires reading the moment—the other person\'s tone, needs and emotional state—not applying a formula. The play uses timing and dialogue to reveal this gap between performed politeness and genuine consideration.',
    ['Tact is choosing the right response for the specific moment, not repeating a memorised line.','Comic timing in theatre depends on placing the mismatch exactly where surprise lands hardest.','Stage directions reveal information that dialogue alone cannot: gesture, movement, expression.','The play argues that empathy makes communication work, while formula makes it break down.'],
    ['Summarise what each character intends in a key scene and what actually happens.','Identify one moment of comic mismatch and explain why it is funny and instructive.','Explain what "tact" means using evidence from the play.','Describe how stage directions contribute to meaning beyond the words spoken.'],
    ['Saying a character is polite because the words sound polite, without examining the effect on the listener.','Describing the comedy only as awkward without explaining why the formula fails here.'],
    ['Intention vs effect','tact needs listening not formula','stage directions show what words hide','comedy teaches consideration']);

  add('g7-english', 'English', 'My Brother\'s Great Invention',
    'Imagination drives invention, but testing always reveals consequences the inventor did not plan; a good narrator separates what she observed from what she believes.',
    'Anita narrates her brother Anand\'s inventions. The first—a burglar alarm—soaks their father, not an intruder. The second is described as a time machine that appears to make a burglar disappear. Whether the burglar genuinely disappeared or simply ran away is never confirmed; the story preserves deliberate ambiguity. Readers must notice that Anita cannot know what happened and must treat her excited conclusion as inference, not evidence.',
    ['Anand is inventive and persistent, but his experiments also show why testing and unintended consequences matter.','The narrator Anita is enthusiastic but not reliable; she presents an inference as a certainty.','The missing burglar keeps the time machine\'s truth deliberately uncertain; the ending asks readers to evaluate evidence.','A responsible reader separates what a narrator observes from what she concludes.'],
    ['Describe each invention: what problem it was meant to solve and what actually happened.','Distinguish between what Anita directly observed and what she infers or assumes.','Explain why the ending is ambiguous and what two interpretations are possible.','State what the story argues about the relationship between imagination, testing and evidence.'],
    ['Saying the time machine definitely worked—the text deliberately preserves uncertainty.','Reading Anita as a fully reliable narrator instead of as an excited sibling who may be wrong.'],
    ['Invention → unintended consequence','Anita observes but infers','missing burglar = ambiguity','evidence ≠ conclusion']);

  add('g7-english', 'English', 'Paper Boats',
    'A small, familiar action can carry a large wish into the world; Tagore uses paper boats on a river to symbolise a child\'s longing for connection with someone unknown and far away.',
    'The child in the poem writes their name on paper boats and fills them with petals before releasing them into the river. The boats travel downstream, past villages, toward the sea, carrying the child\'s identity outward. The poem does not tell us whether anyone ever finds the boats; the act itself is the point. The symbol works because the boats are small and ordinary while the wish they carry—to be known by a stranger somewhere—is large and universal.',
    ['The paper boats are a symbol: small and ordinary objects carrying a large wish for connection.','The river is the medium that carries the child\'s hope outward, beyond what the child can see.','The poem does not resolve whether connection is made; the longing itself is the central experience.','The symbol works because its contrast—tiny boat, enormous wish—is emotionally resonant.'],
    ['Describe what the child does with the boats and why each detail (name, petals) matters.','Explain what the river symbolises in the context of the poem\'s emotional argument.','State what the central longing of the poem is and why it feels universal.','Explain why it matters that the poem does not tell us if anyone finds the boats.'],
    ['Reducing the poem to a craft activity (making paper boats) and missing its symbolic meaning entirely.','Saying the poem is "about nature" without identifying the human longing the natural image carries.'],
    ['Paper boat = small ordinary object','name and petals = child\'s identity and gift','river carries hope outward','longing for unknown connection']);

  add('g7-english', 'English', 'North, South, East, West',
    'Travel writing discovers a country through specific, lived detail; Shaana\'s postcards show that India is not one landscape or one story but an endlessly varied experience.',
    'Shaana sends postcards from a journey across India: Kashmir, Himachal Pradesh, Arunachal Pradesh, the Sundarbans, Gujarat, the Narmada valley, Goa and the southern coast. Each postcard captures one precise observation—a sound, a sight, a conversation—rather than giving general descriptions. The postcard form itself is significant: short, personal, tied to a specific place and moment. The cumulative effect is a portrait of India\'s diversity through a traveller\'s direct experience.',
    ['Travel writing requires selecting vivid, specific details rather than making general statements about a place.','The postcard form is personal, brief and tied to a specific moment and location—these constraints shape the writing.','India\'s diversity is not stated as a fact but shown through accumulating concrete differences of landscape, climate, wildlife and human life.','A reader can use the postcards as a geography and cultural map alongside a personal narrative.'],
    ['Identify the specific detail Shaana notices in each postcard that makes it feel like that place and no other.','Explain how the postcard form (short, personal, place-specific) shapes what can and cannot be said.','Describe the overall picture of India that emerges from all the postcards together.','Compare two postcards: how do landscape and human life differ between the two places?'],
    ['Listing the places Shaana visits as if the postcard is a tourist brochure rather than a personal, specific observation.','Saying India is diverse without showing which specific details in the postcards demonstrate this diversity.'],
    ['Specific detail over general statement','postcard form shapes voice and length','cumulative portrait of India','diversity shown not stated']);

  add('g7-english', 'English', 'The Tunnel',
    'Courage is acting for others despite personal fear; setting concentrates danger and makes an act of bravery meaningful and real.',
    'Suraj, a boy visiting a remote railway station, befriends the elderly watchman Sunder Singh. When a leopard enters the railway tunnel and a train is due, Suraj and Sunder Singh enter the dark tunnel together to drive the leopard out before the train arrives. The tunnel setting concentrates all the danger: darkness, a large animal and an approaching train. The lamp Sunder Singh carries at the end of the story symbolises quiet, daily duty maintained long after the dramatic moment.',
    ['The tunnel concentrates three dangers at once: darkness, a leopard and an approaching train.','Sunder Singh balances duty to passengers with care for the leopard—he wants to drive it out, not harm it.','Suraj\'s courage is not reckless; it follows Sunder Singh\'s experience and lamp-light.','The lamp at the end symbolises ongoing, undramatic duty rather than one heroic moment.'],
    ['Describe the setting of the tunnel and explain how it concentrates danger.','Identify the decisive moment and explain what drives Suraj to act.','Describe Sunder Singh\'s role: is he only a helper, or does he teach something?','Explain what the lamp symbolises at the end of the story.'],
    ['Calling Suraj brave while ignoring Sunder Singh\'s guidance and skilled knowledge of the situation.','Treating the leopard purely as a villain rather than a creature Sunder Singh wants to protect as well as remove.'],
    ['Tunnel = concentrated danger','darkness + leopard + train','Sunder Singh guides and teaches','lamp = quiet ongoing duty']);

  add('g7-english', 'English', 'Travel',
    'The poem expresses the restless human desire for movement and discovery—not toward any specific destination, but toward the experience of being on the way.',
    'The speaker of the poem is drawn by roads, trains, distant horizons and unfamiliar places. The poem repeats images of departure: a road stretching ahead, a train leaving a station, the smell of rain on distant soil. There is no destination named. The longing is for the journey itself, for the feeling of being in motion toward something new. The poem argues—through image and repetition rather than argument—that this restless desire is part of what makes us human.',
    ['The poem does not name a destination; the longing is for movement and experience themselves.','Repeated images of roads, trains and departures build a cumulative feeling that words alone cannot achieve.','A lyric poem expresses a feeling or state of mind rather than narrating a plot.','The poem\'s images are sensory: visual, tactile, even olfactory—this grounds the abstract desire in the body.'],
    ['Identify three images from the poem and explain what each one contributes to the feeling of wanderlust.','Explain why the poem does not name a destination and what effect that choice creates.','Describe the poem as a lyric: what emotion does it express and how does form support it?','Compare the poem\'s desire for travel with Arunima\'s motivation in "Conquering the Summit": how are they different?'],
    ['Treating the poem as a poem about a specific trip or journey, and looking for a destination that is not there.','Describing the poem as simply "happy" or "exciting" without identifying the specific emotion of longing or wanderlust.'],
    ['Road and train = call to move','no destination = the feeling matters','repetition builds longing','lyric form for a state of mind']);

  add('g7-english', 'English', 'Conquering the Summit',
    'Courage is the decision to continue through great difficulty; an achievement of this scale requires rehabilitation, discipline, support and persistent planning over time.',
    'Arunima Sinha was pushed from a moving train by thieves. She lost her leg, was fitted with a prosthetic, and then trained for years under great hardship to climb Mount Everest. She reached the summit on 21 May 2013. The biography shows the full chain: accident → decision to climb → rehabilitation → rigorous training → setbacks → summit. Each stage is equally important; the summit would not have happened without everything that came before it.',
    ['The biography must be read as a chain of decisions and effort, not as a single miraculous act.','Arunima\'s achievement required structured rehabilitation, which is a form of courage and discipline, not passive recovery.','Courage is sustained preparation, not a single dramatic moment—the training months matter as much as the summit day.','The biography shows facts (date, 21 May 2013) and also the inner decisions that made those facts possible.'],
    ['Trace the full chain from the accident to the summit: identify each stage.','Explain why the rehabilitation phase is as important as the climb itself.','Describe what "endurance" means using evidence from Arunima\'s story.','Explain why calling this achievement "sudden" or "miraculous" misrepresents the biography.'],
    ['Presenting Arunima\'s achievement as sudden inspiration and erasing the years of training, pain and support.','Mentioning only the summit date without the decisions and process that made it possible.'],
    ['Accident → decision','rehabilitation = courage too','years of training and setbacks','21 May 2013 = outcome of process']);

  add('g7-english', 'English', 'A Homage to Our Brave Soldiers',
    'A memorial preserves named sacrifice and gives citizens a shared place for remembrance; homage means honouring with evidence, not just with praise words.',
    'The piece introduces the National War Memorial in New Delhi and explains why a memorial matters beyond its physical form. The names carved into the wall individualise sacrifice: each name belongs to a real person who died in service of the country. The writing connects the student\'s ordinary life to the protection that soldiers provide. A homage, the piece argues, is not just admiration—it is recognition of a specific cost paid by specific people for a shared benefit.',
    ['The names on a memorial turn abstract "sacrifice" into real individuals, making gratitude specific rather than general.','A memorial is a public space for shared remembrance—it belongs to every citizen, not only to families of soldiers.','Homage requires naming what was given up (specific sacrifice) and what was protected (shared benefit).','The text connects everyday safety to the specific duty soldiers perform in extreme conditions.'],
    ['Explain what a memorial does that an oral tribute cannot—why does the physical and named form matter?','Identify a specific detail from the text that makes a soldier\'s sacrifice concrete rather than abstract.','Explain the difference between admiration and homage as the text defines it.','Connect the National War Memorial\'s purpose to the idea of shared citizenship.'],
    ['Using only praise words such as "great" and "brave" without specifying what was sacrificed or what was protected.','Treating a memorial as merely a tourist landmark rather than a space of civic memory and recognition.'],
    ['Named sacrifice = specific individuals','memorial = shared civic space','homage needs evidence','everyday life protected by specific duty']);

  add('g7-english', 'English', 'My Dear Soldiers',
    'Direct address in a poem makes gratitude personal and immediate; specific images of harsh terrain and extreme conditions reveal what duty actually costs.',
    'The poet addresses soldiers directly—"my dear soldiers"—and describes the extreme conditions in which they serve: mountain passes in bitter cold, desert borders in intense heat, constant vigilance against threat. By naming specific terrains and weathers, the poem makes the cost of military duty concrete rather than vague. The direct address ("you" rather than "they") creates a feeling of intimate connection between the speaker, who represents every civilian, and the soldiers who protect them.',
    ['Direct address ("you"/"my dear soldiers") closes the distance between civilian life and military service.','Specific terrain images (mountain, desert, cold, heat) make the cost of duty concrete and real, not abstract.','The poem argues that gratitude should be expressed through recognition of specific hardship, not through generic praise.','The speaker represents every citizen who benefits from protection without experiencing its cost.'],
    ['Identify two or three specific terrain or weather images and explain what each reveals about the soldiers\' conditions.','Explain the effect of direct address: why say "you" and "my dear soldiers" rather than "they" or "the soldiers"?','Describe the relationship the poem creates between the speaker and the soldiers.','Compare this poem\'s form of gratitude with the prose piece "A Homage to Our Brave Soldiers": how do they differ?'],
    ['Quoting "brave" or "dedicated" without pointing to specific images from the poem that show why those words apply.','Missing that the poem speaks to soldiers directly and treating it as a description of soldiers written in the third person.'],
    ['"My dear soldiers" = direct address','terrain images = concrete cost of duty','speaker = citizen receiving protection','gratitude through recognition not praise']);

  add('g7-english', 'English', 'Rani Abbakka',
    'Sovereignty is the right of a people to govern themselves without forced submission; Rani Abbakka\'s courage combined strategy, alliance-building and persistence, not only combat.',
    'Rani Abbakka was the queen of Ullal, on the Karnataka coast. When the Portuguese demanded tribute and supremacy over her port, she refused. She formed alliances with neighbouring kingdoms, organised resistance and fought several campaigns. She was eventually betrayed by a family member and captured, but her resistance had lasted for decades and preserved Ullal\'s independence for much of that time. The historical narrative shows that lasting resistance requires intelligence and alliance as much as bravery.',
    ['Rani Abbakka\'s refusal of tribute was a claim of sovereignty—the right of Ullal to govern itself.','Her resistance was strategic: she sought alliances and organised defence rather than relying on individual courage alone.','The eventual betrayal and capture do not cancel the achievement: decades of resistance and the preservation of independence matter.','A historical figure must be evaluated through context, strategy and long-term consequence, not just through dramatic moments.'],
    ['Explain why refusing to pay tribute was a political claim, not simply personal stubbornness.','Describe the strategies Abbakka used beyond direct combat.','Explain why her eventual defeat does not mean her resistance failed.','Evaluate her legacy using evidence from the text: what did her resistance achieve and preserve?'],
    ['Writing Abbakka\'s story as a list of battle dates rather than as claim → strategy → resistance → legacy.','Calling her defeat a failure without acknowledging the decades of sovereignty her resistance preserved.'],
    ['Tribute refusal = sovereignty claim','strategy + alliance not only combat','betrayal and capture ≠ failure','legacy: decades of independence preserved']);


  const hindi = [
    ['माँ, कह एक कहानी','निष्कपट बाल-प्रश्न कहानी को न्याय और करुणा की जाँच में बदल देता है।','माँ और बच्चे के संवाद में कथा केवल मनोरंजन नहीं रहती। बच्चा घटना के पक्षों को सुनकर पूछता है कि शक्तिशाली और निर्बल, दंड और दया, नियम और न्याय में सही चुनाव क्या है; यही प्रश्नशीलता पाठ का नैतिक केन्द्र बनती है।',['संवाद से वक्ता, श्रोता और दृष्टिकोण पहचानो।','बालक की जिज्ञासा तैयार उत्तर को चुनौती देती है।','नैतिक निर्णय में घटना, उद्देश्य और दूसरे पर प्रभाव—तीनों देखे जाते हैं।'],['कथा की मुख्य घटना लिखो।','माँ के कथन और बालक के प्रश्न का अंतर बताओ।','प्रश्न से खुलने वाली नैतिक दुविधा समझाओ।','अपना निर्णय पाठ-संकेत से सिद्ध करो।'],['पूरी कथा दोहराकर बालक के प्रश्न को छोड़ देना।','“सीख” लिखना पर न्याय/करुणा का कारण न देना।'],['माँ सुनाती है','बालक पूछता है','मान्यता की जाँच होती है','करुणा सहित न्याय']],
    ['तीन बुद्धिमान','बुद्धिमत्ता का प्रमाण नाम या दावा नहीं, उचित उपाय और उसका परिणाम है।','लोककथा तीन पात्रों की युक्तियों को हास्य के साथ सामने रखती है। समस्या को किसने ठीक समझा, किसने केवल चतुर दिखने की कोशिश की और किस उपाय ने लाभ या हानि पहुँचाई—इन परिणामों से असली विवेक पहचाना जाता है।',['समस्या और बाधा अलग हैं।','युक्ति को उसके परिणाम से जाँचो।','व्यंग्य मूर्खता या अहंकार को बिना उपदेश के उजागर करता है।'],['समस्या बताओ।','तीनों प्रतिक्रियाओं की तुलना एक ही कसौटी पर करो।','हर उपाय का परिणाम लिखो।','बताओ कौन सचमुच बुद्धिमान और क्यों।'],['“तीन” पात्रों को तीनों बुद्धिमान मान लेना।','हास्य घटना लिखना पर उसके भीतर की आलोचना न समझाना।'],['समस्या','तीन उपाय','तीन परिणाम','विवेक = सही संदर्भ + अच्छा परिणाम']],
    ['फूल और काँटा','एक ही प्रकृति में जन्म लेकर भी कर्म और प्रभाव अलग पहचान बनाते हैं।','कविता फूल और काँटे के विपरीत बिंबों से कोमलता–कठोरता, सुख–पीड़ा और सद्कर्म–दुष्कर्म का अंतर रचती है। बाहरी परिस्थिति समान होने पर भी दूसरों के जीवन पर हमारा प्रभाव हमारे चरित्र को प्रकट करता है।',['फूल और काँटा प्रतीक हैं, केवल वनस्पति नहीं।','विरोधी बिंब तुलना को स्पष्ट बनाते हैं।','कर्म से पहचान बनने का संदेश कविता की व्यापक परत है।'],['दोनों के समान स्रोत को पहचानो।','गुण और प्रभाव की जोड़ी बनाओ।','प्रतीक का मानव-जीवन अर्थ लिखो।','एक पाठ-संकेत से निष्कर्ष सिद्ध करो।'],['फूल को अच्छा और काँटे को बुरा कहकर रुक जाना।','उपमा/प्रतीक का नाम देकर उसका प्रभाव न लिखना।'],['समान प्रकृति','विपरीत गुण','अलग प्रभाव','कर्म बनाता पहचान']],
    ['पानी रे पानी','जल बहती वस्तु नहीं, जीवन को जोड़ने वाला सीमित और साझा चक्र है।','काव्यात्मक संबोधन पानी को बोलते हुए साथी जैसा बनाता है, जबकि पाठ जल की यात्रा, उपयोग और संकट पर सोचने को कहता है। वर्षा से संग्रह, भूमि और नदी से उपयोग, फिर वाष्पीकरण—चक्र बचा रहे तो जीवन चलता है; प्रदूषण और अपव्यय इसे बिगाड़ते हैं।',['मानवीकरण पानी से भावनात्मक संबंध बनाता है।','जलचक्र में संग्रह, बहाव, भूजल और वाष्पीकरण जुड़े हैं।','संरक्षण का उत्तर स्थानीय कारण और मापने योग्य उपाय माँगता है।'],['पानी की भूमिका पहचानो।','समस्या का स्थानीय कारण बताओ।','उसके जीवन/पर्यावरण प्रभाव को जोड़ो।','रिसाव रोकना, पुनःउपयोग या वर्षाजल-संचयन जैसा ठोस उपाय दो।'],['केवल “जल ही जीवन है” लिखना।','जलचक्र और जल-संरक्षण को बिना कारण जोड़े सूची बनाना।'],['वर्षा','संग्रह','उपयोग','पुनर्चक्रण—हर बूँद साझा']],
    ['नहीं होना बीमार','स्वास्थ्य डर से नहीं, कारण समझकर अपनाई गई नियमित आदतों से बनता है।','लय और हास्य से दिया गया स्वास्थ्य-संदेश शरीर की देखभाल को बोझ नहीं रहने देता। स्वच्छता, भोजन, व्यायाम और विश्राम जैसी आदतें तभी अर्थपूर्ण हैं जब छात्र बता सके कि वे संक्रमण या कमजोरी की कड़ी कहाँ तोड़ती हैं।',['लक्षण, रोग का कारण और रोकथाम अलग अवधारणाएँ हैं।','निर्देश के साथ कारण लिखने से उत्तर वैज्ञानिक बनता है।','हास्य और लय संदेश को याद रखने योग्य बनाते हैं।'],['स्वास्थ्य-समस्या पहचानो।','संबंधित आदत बताओ।','आदत किस जोखिम को घटाती है, समझाओ।','कविता के लहजे का प्रभाव जोड़ो।'],['घरेलू उपचार को चिकित्सा-निदान की तरह प्रस्तुत करना।','“स्वस्थ भोजन करो” जैसे अस्पष्ट निर्देश देना।'],['साफ रहो','संतुलित खाओ','चलो–खेलो','सोओ; बीमारी पर जिम्मेदार बड़े/चिकित्सक']],
    ['गिरिधर कविराय की कुंडलियाँ','कुंडलिया का घूमकर आरम्भ से जुड़ना नीति-विचार को भाषा और स्मृति दोनों में बाँधता है।','गिरिधर कविराय रोजमर्रा के आचरण को संक्षिप्त, लयबद्ध कथनों में परखते हैं। पहली पंक्ति का अंश अंत में लौटता है; इसलिए रूप स्वयं संदेश को फिर सामने लाता है और पाठक से उसे जीवन में लागू करने को कहता है।',['कुंडलिया में दोहा और रोला की संरचना जुड़ती है।','आरम्भिक शब्द अंत में लौटने से “कुंडली” बनती है।','भावार्थ में शाब्दिक अर्थ, नीति और आज का उदाहरण चाहिए।'],['कठिन शब्दों का सरल अर्थ करो।','कवि की सलाह एक वाक्य में लिखो।','रचना में पुनरावृत्ति/लय का प्रभाव बताओ।','वर्तमान जीवन का उचित उदाहरण दो।'],['छंद की परिभाषा लिखकर पद का भाव भूल जाना।','लोकोक्ति को हर परिस्थिति में बिना विवेक लागू करना।'],['दोहा + रोला','अंत में आरम्भ','संक्षिप्त नीति','जीवन-उदाहरण']],
    ['वर्षा-बहार','वर्षा के दृश्य, ध्वनि, गंध और गति मिलकर बाहर की ऋतु और भीतर का उल्लास रचते हैं।','कविता बादल, बूँद, हरियाली, हवा और जीव-जगत की गतिविधि से सूखे परिवेश का रूपान्तरण दिखाती है। वर्षा केवल मौसम नहीं; शब्दों की ध्वनि और गतिशील क्रियाएँ पाठक को उस बदलते वातावरण में ले जाती हैं।',['इंद्रिय-बिंब वातावरण बनाते हैं।','ध्वन्यात्मक शब्द वर्षा को सुनने योग्य बनाते हैं।','प्रकृति का परिवर्तन मनोदशा के परिवर्तन से जुड़ता है।'],['वर्षा से पहले का दृश्य लिखो।','आने के संकेत और ध्वनियाँ पहचानो।','बाद का रंग/गति/जीवन बताओ।','किसी बिंब से भाव सिद्ध करो।'],['विशेषण गिनना पर बिंब का प्रभाव न बताना।','हर वर्षा-वर्णन को केवल “सुंदर” कहना।'],['बादल','बूँदों की ध्वनि','हरियाली','मन में बहार']],
    ['बिरजू महाराज से साक्षात्कार','कला की महानता मंच पर दिखती है, पर उसके पीछे साधना, परम्परा, प्रयोग और संवेदना होती है।','साक्षात्कार बिरजू महाराज के कथक-जीवन को प्रश्न–उत्तर में खोलता है। उत्तर उनके प्रशिक्षण, लय–भाव की समझ, गुरु-परम्परा और कला-दृष्टि को सामने लाते हैं; अच्छा पाठक अगला प्रश्न पिछले उत्तर से बनाता है।',['साक्षात्कार में खुले और अनुवर्ती प्रश्न गहरी जानकारी देते हैं।','कथक कथा, लय, पदचालन, मुद्रा और भाव का संयुक्त रूप है।','जीवन-वृत्त के तथ्य और कलाकार के विचार अलग नोट करो।'],['प्रश्न का विषय पहचानो।','उत्तर से प्रमुख तथ्य और दृष्टि अलग करो।','कला के अभ्यास/चुनाव से जोड़ो।','बताओ प्रश्न कलाकार को कैसे खोलता है।'],['साक्षात्कार को जीवनी की कालक्रम-सूची बना देना।','हाँ/नहीं वाले कमजोर प्रश्नों को प्रभावी मानना।'],['प्रश्न','उत्तर','अनुवर्ती प्रश्न','साधना से कला-दृष्टि']],
    ['चिड़िया','छोटी चिड़िया स्वतंत्रता, नाजुकता और बार-बार उठ खड़े होने की बड़ी मानवीय आकांक्षा बनती है।','कविता चिड़िया की उड़ान, स्वर, बसेरे और सीमाओं के बीच गति को देखकर एक छोटे जीव में साहस और स्वाधीनता खोजती है। प्रतीक का अर्थ मनमाना नहीं; उसकी क्रियाओं, स्थान और स्वर के दो या अधिक संकेतों से सिद्ध होता है।',['चिड़िया का शाब्दिक रूप और प्रतीकात्मक अर्थ साथ चलते हैं।','आकाश/पिंजरा, उड़ान/बंधन जैसे विरोध अर्थ को गहरा करते हैं।','लघु बिंब से व्यापक विचार निकलता है।'],['चिड़िया की मुख्य क्रियाएँ चुनो।','सीमा और खुले स्थान का विरोध देखो।','दो संकेतों से प्रतीक का अर्थ बनाओ।','उस अर्थ को कविता के भाव से जोड़ो।'],['चिड़िया को केवल प्रकृति-वर्णन मानना।','एक पंक्ति से मनचाहा प्रतीक निकालना।'],['छोटी देह','खुला आकाश','उड़ान की जिजीविषा','स्वतंत्रता का प्रतीक']],
    ['मीरा के पद','मीरा की भक्ति निजी प्रेम, पूर्ण समर्पण और सामाजिक दबाव के सामने आत्मिक स्वतंत्रता की आवाज है।','पदों में मीरा कृष्ण को आराध्य और प्रियतम मानकर सीधे संबोधित करती हैं। सांसारिक मान–अपमान से ऊपर उठी उनकी निष्ठा विरह, प्रेम और मिलन की इच्छा को एक साथ रखती है; इसलिए व्यक्तिगत स्वर सार्वभौमिक अनुभव बन जाता है।',['भक्त–आराध्य संबंध पद का केन्द्र है।','संबोधन, पुनरावृत्ति और भाव-सूचक शब्द समर्पण तीव्र करते हैं।','ऐतिहासिक संदर्भ सहायक है, पर भावार्थ का स्थान नहीं लेता।'],['वक्ता और संबोधित को पहचानो।','मुख्य भाव—भक्ति, विरह या समर्पण—चुनो।','शब्द/बिंब से भाव सिद्ध करो।','बताओ यह निष्ठा किस दबाव को चुनौती देती है।'],['मीरा की जीवनी लिखकर पद की भाषा भूल जाना।','भक्ति को निष्क्रियता समझना; यहाँ चुनाव और दृढ़ता भी है।'],['मीरा का सीधा संबोधन','कृष्ण के प्रति निष्ठा','विरह + समर्पण','भीतर की स्वतंत्रता']]
  ];
  hindi.forEach(args => add('g7-hindi', 'Hindi', ...args));

  const tamil = [
    ['அமுதத் தமிழ்','தமிழின் இனிமை அதன் பழமையில் மட்டும் அல்ல; எண்ணத்தைத் தெளிவாகவும் சூழலுக்கு ஏற்றவாறும் வெளிப்படுத்தும் உயிர்ப்பில் உள்ளது.','இந்த இயல் தமிழின் சிறப்பு, பேச்சுமொழி–எழுத்துமொழி வேறுபாடு, சொலவடை மற்றும் ஒலிப்புமுறைகளை ஒன்றாகக் காட்டுகிறது. மொழிப்பற்று என்பது புகழ்வது மட்டும் அல்ல; பொருத்தமான சொல்லைத் தேர்ந்து, இலக்கண ஒழுங்குடன், பிறர் புரியும்படி பயன்படுத்துவதாகும்.',['பேச்சுமொழி இயல்பான உரையாடலுக்கேற்ப மாறும்; எழுத்துமொழி தெளிவும் ஒழுங்கும் கோரும்.','சொலவடை குறைந்த சொற்களில் அனுபவ அறிவைத் தருகிறது.','குற்றியலுகரம்/குற்றியலிகரம் போன்ற ஒலிமாற்றங்களைச் சொல்லில் கண்டறிந்து வாசிக்க வேண்டும்.'],['பேசுபவர், கேட்பவர், நோக்கம் ஆகியவற்றைக் கண்டறி.','அதற்கேற்ற மொழிநடையைத் தேர்ந்தெடு.','சொல்/ஒலிக்கூறை எடுத்துக்காட்டில் காட்டு.','அது கருத்தை எவ்வாறு தெளிவாக்குகிறது என்று விளக்கு.'],['தமிழை “இனிய மொழி” என்று மட்டும் எழுதுதல்.','பேச்சுமொழியைப் பிழை என்றும் எழுத்துமொழியை மட்டும் சரி என்றும் கருதுதல்.'],['சூழல்','சொல் தேர்வு','ஒலி–இலக்கண ஒழுங்கு','தெளிவான தமிழ்']],
    ['அணிநிழல் காடு','காடு தனித்தனி மரங்களின் கூட்டம் அல்ல; மண், நீர், தாவரம், விலங்கு, மனிதர் இணைந்த உயிர்வலை.','இயற்கை வருணனையும் நேர்காணல் பார்வையும் காட்டு வாழ்வின் பரஸ்பரச் சார்பை வெளிப்படுத்துகின்றன. ஒரு உயிரினம் அல்லது நீர்வளம் குறைந்தால் உணவுச் சங்கிலி, மண் வளம், மனித வாழ்வாதாரம் வரை தாக்கம் செல்கிறது.',['உணவுச் சங்கிலியின் ஒவ்வொரு இணைப்பும் மற்ற உயிர்களின் எண்ணிக்கையைப் பாதிக்கும்.','மரநிழல் நீரைத் தக்கவைத்து மண்ணரிப்பைக் குறைக்க உதவும்.','நேர்காணலில் திறந்த வினா அனுபவத்தையும் ஆதாரத்தையும் வெளிக்கொணரும்.'],['காட்டின் ஒரு கூறைத் தேர்ந்தெடு.','அது சார்ந்துள்ள கூறுகளை இணை.','ஒரு மாற்றத்தின் தொடர் விளைவைக் காட்டு.','பாதுகாப்பு நடவடிக்கையை காரணத்துடன் கூறு.'],['காட்டைப் பசுமையான காட்சி என்று மட்டும் சுருக்குதல்.','விலங்கு பாதுகாப்பையும் வாழிட பாதுகாப்பையும் பிரித்துப் பார்ப்பது.'],['மண் + நீர்','தாவரம்','விலங்கு','மனிதன்—ஒரே உயிர்வலை']],
    ['நாடு அதை நாடு','நாட்டுப்பற்று முழக்கமல்ல; வரலாற்றை ஆதாரத்துடன் அறிந்து பொதுநலத்திற்குப் பொறுப்பேற்பது.','வீரம் மற்றும் விடுதலை வரலாற்றைப் பேசும் பாடங்கள், ஒரு நாட்டை நேசிப்பது அதன் மக்களின் கண்ணியம், உரிமை, ஒற்றுமையை காப்பதில் தெரிகிறது என்பதை வலியுறுத்துகின்றன. ஆளுமையின் பெருமை அவர் எதிர்கொண்ட இடர், எடுத்த முடிவு, உருவாக்கிய சமூக விளைவு ஆகியவற்றால் நிரூபிக்கப்படுகிறது.',['வரலாற்று நிகழ்வில் காலம், இடம், காரணம், விளைவு தேவை.','வீரம் என்பது ஆபத்து + நெறியுள்ள நோக்கம் + செயல்.','வினைமுற்று காலத்தையும் செயல் நிறைவையும் தெளிவாக்குகிறது.'],['ஆளுமை/நிகழ்வைச் சரியாக அமை.','எதிர்கொண்ட இடரைச் சொல்.','குறிப்பிட்ட செயலை ஆதாரமாகக் கொடு.','நாடு அல்லது மக்களுக்கான விளைவை விளக்கு.'],['புகழ்ச்சிச் சொற்கள் மட்டும் எழுதுதல்.','நிகழ்வுகளைக் காலவரிசையின்றி கலத்தல்.'],['இடர்','நெறியுள்ள தேர்வு','துணிவான செயல்','பொதுநல விளைவு']],
    ['அறிவியல் ஆக்கம்','அறிவியல் விளக்கம் பொருளின் பெயரல்ல; பகுதி, செயல், காரணம், பயன் ஆகியவற்றின் துல்லியமான தொடர்.','கப்பற்கலை மற்றும் தொழில்நுட்ப ஆக்கங்கள் தமிழில் அறிவியல் சிந்தனையை வெளிப்படுத்துகின்றன. ஒரு கருவி அல்லது அமைப்பைப் புரிந்துகொள்ள உள்ளீடு எது, எந்தப் பகுதிகள் என்ன செய்கின்றன, மாற்றம் எப்படி நடக்கிறது, வெளியீடு/பயன் என்ன என்பதைக் காரண வரிசையில் பார்க்க வேண்டும்.',['தொழில்நுட்பச் சொல்லுக்கு ஒரே தெளிவான பொருள் வேண்டும்.','வரைபடத்தில் பகுதி பெயரும் செயல்திசையும் குறிக்க வேண்டும்.','உள்ளீடு → செயல்முறை → வெளியீடு என்பது வலுவான விளக்க எலும்புக்கூடு.'],['கருவி/ஆக்கத்தின் நோக்கத்தைச் சொல்.','முக்கிய பகுதிகளைப் பெயரிடு.','செயல்களை சரியான வரிசையில் அமை.','காரணம், விளைவு, பயன் மூலம் முடி.'],['பகுதிப் பட்டியலை செயல்முறை என நினைத்தல்.','“பிறகு” மட்டும் பயன்படுத்தி ஏன் நடைபெறுகிறது என்பதை விடுதல்.'],['நோக்கம்','பகுதிகள்','செயல்முறை','பயன்']],
    ['ஓதுவது ஒழியேல்','கல்வி மனப்பாடச் சேமிப்பு அல்ல; சிந்திக்க, தேர்வு செய்ய, வாழ்வை மாற்றப் பயன்படும் ஆற்றல்.','கல்வியின் மதிப்பை மையமாகக் கொண்ட இந்த இயல், அறிவு பயன்படுத்தும்போது வளர்வதையும் அது தனிமனித வாய்ப்புடன் சமூக முன்னேற்றத்தையும் உருவாக்குவதையும் காட்டுகிறது. “ஓதுவது ஒழியேல்” தொடர்ச்சியான கற்றலை வாழ்நாள் பழக்கமாக்கும் அழைப்பு.',['கல்வி அறிவு, திறன், மதிப்பு, முடிவெடுப்பு ஆகியவற்றை இணைக்கிறது.','பொருட்செல்வம் குறையலாம்; பயன்படுத்திய அறிவு வளரலாம்.','சொல் அமைப்பு/இலக்கணக் கூறு புதிய வாக்கியத்தில் பயன்பட்டால்தான் கற்றல் உறுதி.'],['கல்வி தரும் மாற்றத்தைத் தேர்ந்தெடு.','அதற்கான காரணத்தை பாடக்கருத்துடன் இணை.','வாழ்க்கை எடுத்துக்காட்டு கொடு.','தனி நபர் மற்றும் சமூக விளைவைச் சொல்.'],['“கல்வி முக்கியம்” என்று காரணமின்றி எழுதுதல்.','மதிப்பெண் பெறுதலையே கல்வியின் முழுப் பயன் எனக் கூறுதல்.'],['தொடர்ந்து ஓது','புரிந்து சிந்தி','பயன்படுத்து','உன்னையும் சமூகத்தையும் உயர்த்து']],
    ['கலைவண்ணம்','கலைப்பார்வை என்பது “அழகு” என்று சொல்வதல்ல; நிறம், கோடு, வடிவம், இடவமைப்பு உருவாக்கும் பொருளை வாசிப்பது.','ஓவியம் மற்றும் பிற கலைவடிவங்கள் சொல்லில்லாமலும் கதை, உணர்வு, காலம், பண்பாட்டைத் தெரிவிக்கின்றன. பார்வை முதலில் எங்கு செல்கிறது, எந்த நிற/கோடு அதை வழிநடத்துகிறது, அதனால் என்ன உணர்வு உருவாகிறது என ஆராய்ந்தால் ரசனை ஆதாரமுள்ள விளக்கமாக மாறுகிறது.',['மையப்புள்ளி பார்வையை முதலில் ஈர்க்கும் பகுதி.','சூடான/குளிர்ந்த நிறங்கள், நேரான/வளைந்த கோடுகள் வேறு மனநிலைகளை உருவாக்கலாம்.','தொழிற்பெயர் செயலை ஒரு பெயராக்குகிறது; வடிவத்தை வாக்கியத்தில் அறிய வேண்டும்.'],['முதலில் காணும் பகுதியைக் குறி.','நிறம், கோடு, வடிவம், இடைவெளியில் ஆதாரம் தேர்வு செய்.','அவை உருவாக்கும் உணர்வை விளக்கு.','மையக்கருத்துடன் இணை.'],['ஓவியத்தில் உள்ள பொருட்களை மட்டும் பட்டியலிடுதல்.','தனிப்பட்ட விருப்பத்தை ஆதாரமில்லா மதிப்பீடாக எழுதுதல்.'],['என்ன காண்கிறேன்?','எது பார்வையை இழுக்கிறது?','எப்படி உணர வைக்கிறது?','என்ன கருத்து?']],
    ['நயத்தகு நாகரிகம்','நாகரிகம் கட்டடங்களில் மட்டும் இல்லை; வளத்தைப் பயன்படுத்தும் அறிவு, விருந்தோம்பல், தொழில், நீர்மேலாண்மை, சமூக உறவில் உள்ளது.','பழந்தமிழர் வாழ்வின் வயல், உணவு, விருந்தோம்பல், தொழில் மற்றும் பண்பாட்டு நடைமுறைகள் ஒன்றுக்கொன்று துணைநிற்கும் சமூக அமைப்பை உருவாக்கின. இலக்கியச் சான்றை வைத்து ஒரு நடைமுறை எவ்வாறு நம்பிக்கை, பகிர்வு, நிலைத்த வாழ்வை வளர்த்தது என விளக்க வேண்டும்.',['விருந்தோம்பல் வளப் பகிர்வையும் உறவையும் உருவாக்குகிறது.','விவசாயம் நீர், நிலம், காலம், உழைப்பு பற்றிய கூட்டு அறிவைச் சார்ந்தது.','அணி இலக்கணத்தில் கருவிப் பெயருடன் கருத்தின் தாக்கமும் தேவை.'],['பண்பாட்டு நடைமுறையை அடையாளம் காண்.','பாடச் சான்றைக் கொடு.','அதன் சமூக/பொருளாதார செயல்பாட்டை விளக்கு.','இன்றைய வாழ்வுடன் பொருத்தமாக ஒப்பிடு.'],['நாகரிகம் = பழமை என்று மட்டும் கருதுதல்.','சான்றை மேற்கோள் காட்டி அதன் பொருளை விளக்காமை.'],['வளம்','பகிர்வு','தொழில் அறிவு','நம்பிக்கைமிக்க சமூகம்']],
    ['ஒப்புரவு ஒழுகு','ஒப்புரவு என்பது எல்லோருக்கும் ஒன்றையே கொடுப்பது அல்ல; தேவையை உணர்ந்து கண்ணியத்துடன் தக்க உதவி செய்வது.','அறநெறிப் பாடங்கள் தனி உதவியைத் தாண்டி, எதிர்பார்ப்பின்றிப் பொதுநலனுக்காகச் செயல்படும் பண்பை எடுத்துரைக்கின்றன. உருவகமும் அணியும் இந்த அறத்தை நினைவில் நிற்கும் காட்சியாக மாற்றுகின்றன; உதவி பெறுபவரின் கண்ணியம் காக்கப்படுவதே அளவுகோல்.',['சமத்துவம் ஒரே வாய்ப்பு; ஒப்புரவு தேவைக்கேற்ற ஆதரவு என வேறுபடலாம்.','நல்ல நோக்கம் மட்டும் போதாது; செயல் உண்மையில் உதவ வேண்டும்.','உருவகம் ஒரு கருத்தை மற்றொரு காட்சியின் வழி உணர்த்துகிறது.'],['தேவையைத் தெளிவாகக் கண்டறி.','செயலின் நோக்கமும் முறையும் கூறு.','பெறுபவரின் கண்ணியம்/விளைவைக் கணக்கு.','பொதுநலத்துடன் இணை.'],['ஒப்புரவைப் புகழ் பெறும் நன்கொடையாகக் குறைத்தல்.','பெறுபவரின் விருப்பம் கேட்காமல் உதவுவது எப்போதும் நல்லது என நினைத்தல்.'],['தேவையை உணர்','கேட்டு அறி','தக்க உதவி செய்','கண்ணியம் + பொதுநலம்']],
    ['மானுடம் வெல்லும்','மனிதநேயம் வேறுபாடுகளை அழிப்பதல்ல; அவற்றை மதித்தபடி ஒவ்வொருவரின் கண்ணியம் மற்றும் சமத்துவத்தைக் காப்பது.','ஆளுமை மற்றும் மனிதம் பற்றிய பாடங்கள், கடினமான சூழலில் ஒருவர் எடுக்கும் முடிவே அவரது மதிப்புகளை வெளிப்படுத்தும் என்று காட்டுகின்றன. இரக்கம் உணர்வாகத் தொடங்கினாலும், பாகுபாட்டைத் தடுத்து உரிமையைப் பாதுகாக்கும் செயலாக மாறும்போது மானுடம் வெல்லும்.',['மனித கண்ணியம் அனைவருக்கும் உரியது.','ஆளுமையை சொல் அல்ல, தேர்வு மற்றும் விளைவால் மதிப்பிட வேண்டும்.','ஆகுபெயரில் தொடர்புடைய பெயர் வேறொரு பொருளைக் குறிக்கும்; சூழல் பொருளைத் தீர்மானிக்கும்.'],['கடினமான சூழலை அடையாளம் காண்.','ஆளுமையின் தேர்வைச் சொல்.','அது யாருடைய கண்ணியத்தை எப்படிக் காத்தது என்று விளக்கு.','பொதுவான மனிதநேயக் கருத்துடன் முடி.'],['மனிதநேயத்தை இரக்கம் மட்டும் எனச் சுருக்குதல்.','தலைவரைப் புகழ்ந்து குறிப்பிட்ட முடிவைச் சொல்லாமை.'],['வேறுபாட்டை மதிப்பு','கண்ணியத்தைக் காப்பு','சமத்துவமாகச் செயல்','மானுடம் வெல்லும்']]
  ];
  tamil.forEach(args => add('g7-tamil', 'Tamil', ...args));

  const skills = [
    ['Work with Life Forms — Part 1','Living things must be observed and cared for ethically; a fair investigation changes one condition and records what truly happens.','This project foundation turns plants, soil or other life forms into partners in careful observation—not disposable equipment. Students identify needs, protect welfare, compare matched conditions and keep dated evidence so that a conclusion follows from observations rather than hopes.',['Need first: organism, habitat, water/light/food and possible harm.','Fair test: one changed variable, matched controls and repeated observations.','Care cycle: observe → care safely → record → adjust.','Wash hands; never taste unknown plants or handle wildlife.'],['Write one answerable question.','Choose the single variable to change and all conditions to keep equal.','Plan safe care and a dated observation table.','Compare evidence, state a limitation and propose the next test.'],['Changing light, water and container together.','Hiding failed growth instead of treating it as evidence.','Removing organisms from habitats without permission.'],['need before task','one changed variable','dated evidence','care comes before result']],
    ['School Habitat Garden','A habitat garden is a working web of soil, water, native plants, insects and people—not outdoor decoration.','Students survey sunlight, drainage, existing species and foot traffic before designing layers of safe, locally suitable plants. They then assign maintenance, monitor survival and biodiversity, and improve the habitat across seasons.',['Map sun, shade, waterlogging, utilities, paths and hazards.','Choose non-toxic, non-invasive, locally suitable plants for food and shelter niches.','Mulch and planned watering reduce loss.','Measure survival, flowering, visitor species, soil cover and water use.'],['Survey and draw the site.','Set habitat and user success criteria.','Choose species with reasons and school approval.','Plant safely, maintain on a rota and compare before/after evidence.'],['Choosing plants from appearance alone.','No watering plan for holidays.','Calling plant count “biodiversity” without observing species relationships.'],['survey before planting','right plant, right place','layers create habitat','maintain and measure']],
    ['Work with Machines and Materials — Part 2','Engineering improves a useful result by matching material properties and shape to forces, then testing safely.','Students move from sketch to prototype instead of guessing. Levers, wheels, gears or structural folds redirect force; strength, flexibility, weight, cost and reuse guide material choice. Each test changes one weakness and produces the next design decision.',['Input force passes through a mechanism to useful motion.','Material choice follows need → required property → candidate → test.','Triangular, folded or deep sections can stiffen a structure without simply adding mass.','Clamp work, cut away from the body and use powered tools only with trained adult supervision.'],['Define user need and measurable success.', 'Sketch dimensions, joints, force directions and materials.', 'Build a small safe prototype.', 'Test one criterion, record failure, change one feature and retest.'],['Testing unstable heavy loads near hands or feet.','Changing shape and material simultaneously, so the improvement cannot be explained.','Showing a final product without version evidence.'],['force chooses mechanism','property chooses material','test exposes weakness','one revision at a time']],
    ['AI Assistant','AI can generate useful patterns quickly, but truth, privacy and responsibility remain human jobs.','Students learn to specify a task without exposing personal data, compare outputs, verify claims through trusted sources or direct tests, and document corrections. Fluent wording is never treated as proof, especially for health, safety, money or identity decisions.',['Prompt = task + safe context + constraints + output format.','Generative AI may confidently invent facts and citations.','Verification means opening the source, checking the relevant claim and testing calculations.','Never upload passwords, faces, private records or identifying student data without authorised safeguards.'],['Define what a successful answer must contain.','Remove private or unnecessary data before prompting.','Generate a draft, mark each checkable claim and verify independently.','Correct, cite/disclose meaningful assistance and make the final decision yourself.'],['Trusting confidence as accuracy.','Inventing a source because an AI supplied a plausible title.','Using AI health or safety advice without a qualified adult/expert.'],['ask clearly','protect data','verify independently','human owns the decision']],
    ['Work in Human Services — Part 3','Good service helps with people, not to people: listen, obtain consent, remove barriers and respect role boundaries.','A student service project begins with the user’s stated need. Language, timing, physical access and privacy are adapted so the person retains agency. When medical, legal, financial or safety risk exceeds the student’s competence, dependable service means referring to an authorised adult or professional.',['Open questions discover needs; confirmation prevents assumption.','Consent continues and may be withdrawn when scope or audience changes.','Accessibility removes a specific barrier rather than treating everyone identically.','Minimum necessary data and appropriate referral protect users.'],['Listen privately and clarify the desired outcome.','Agree on what help and information use are acceptable.','Deliver an accessible step while letting the user choose.','Check the outcome, document anonymously and refer anything outside the safe role.'],['Photographing or publishing beneficiaries without consent.','Taking control because helping feels efficient.','Promising secrecy when someone may be unsafe.'],['listen','clarify and consent','adapt access','support within role; refer risk']],
    ['Family Health Handbook','A family health handbook organises verified routines and emergency access; it records authorised guidance but never diagnoses or changes treatment.','Students design a clear, private handbook that separates urgent action, preventive routines, contacts and record templates. Every public-health claim carries a trustworthy source and review date, while personal details remain adult-controlled and limited to what the family agrees to store.',['Emergency pages lead to trained help; they do not offer diagnosis.','Medicine records copy the prescribed name, dose and time exactly; changes belong to the prescriber.','Source, date and review date make health information maintainable.','Use plain language and icons; never colour alone to show urgency.'],['Separate emergency, routine, record and contact sections.','Choose official/qualified sources and note review dates.','Collect only consented minimum family details.','Adult-review the handbook, protect access and schedule updates.'],['Copying social-media remedies as fact.','Publishing family diagnoses in a school project.','Telling someone to change or double a missed medicine dose.'],['verify source','simplify action','protect privacy','diagnosis and treatment stay professional']],
    ['Planning for Kaushal Mela','A successful mela connects every learning exhibit to a purpose, owner, deadline, safety control and tested backup.','Students turn an exciting event into a work breakdown: exhibits, materials, permissions, budget, accessibility, visitor flow and feedback. Rehearsal reveals dependencies and risks before opening; the final review judges learning and inclusion, not crowd size alone.',['A dependency must finish before another task can start.','Every task needs one accountable owner and date.','Electrical setups, tools, food and living things need specific adult-approved controls.','Success measures include learning, safety, reliability, inclusion and visitor evidence.'],['Define learning goals and must-have deliverables.','Break work into owned tasks, dependencies, budget and timeline.','Design the visitor journey and accessible explanations.','Rehearse, inspect risks, prepare backups, run and debrief with evidence.'],['Assigning a task to “everyone”.','Leaving safety inspection until event morning.','Measuring success only by attendance or decoration.'],['purpose','owner + deadline','test + safety','backup + evidence-based review']]
  ];
  skills.forEach(args => add('g7-skills', 'Kaushal Bodh', ...args));
})();
