const {test,expect}=require('@playwright/test');
test('compact education grid, contextual notes, study guide and embedded PDF',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:8765/#/study/curriculum');await page.evaluate(()=>localStorage.clear());await page.reload();
 const math=page.locator('.education-class').last().locator('.education-subject').filter({has:page.locator('summary').filter({hasText:/^Mathematics/})});if(!await math.evaluate(node=>node.open))await math.locator('summary').click();await math.locator('[data-education-page="study/curriculum"]').click();
 await expect(page.locator('.header-actions #personaSwitcher')).toBeVisible();await expect(page.locator('#sidebar #personaSwitcher')).toHaveCount(0);await expect(page.locator('#workspaceMenuLabel')).toBeHidden();
 const row=page.locator('.progress-slider-row').first();expect((await row.boundingBox()).height).toBeLessThan(80);await expect(row.locator('[data-progress-level]')).toHaveCount(3);await expect(math.locator('[data-education-page="study/curriculum"]')).toHaveAttribute('aria-current','page');
 await row.locator('[data-chapter-notes]').click();await expect(page.locator('#chapterNotesDrawer')).toBeVisible();await page.locator('#chapterNoteText').fill('Remember place values');await expect(page.locator('.notes-save-status')).toHaveText('Saved');await page.locator('[data-close-notes]').last().click();await row.locator('[data-chapter-notes]').click();await expect(page.locator('#chapterNoteText')).toHaveValue('Remember place values');await page.keyboard.press('Escape');
 await math.locator('[data-education-page="learning"]').click();await expect(page.locator('.guide-hero')).toBeVisible();await expect(page.locator('.guide-card')).toHaveCount(11);await expect(page.locator('.education-workspace-toolbar .content-learning-tabs')).toBeVisible();await expect(page.locator('.education-workspace-toolbar [data-study-section]')).toHaveCount(3);await page.screenshot({path:'test-results/education-guide-modern.png'});
 await page.locator('.education-workspace-toolbar [data-chapter-notes]').click();await expect(page.locator('#chapterNoteText')).toHaveValue('Remember place values');await page.keyboard.press('Escape');await expect(page.locator('.guide-hero')).toBeVisible();
 await math.locator('[data-education-page="book"]').click();const reader=page.frameLocator('.education-pdf');await expect(reader.locator('#status')).toBeHidden({timeout:60000});expect(await reader.locator('canvas').evaluate(canvas=>canvas.width)).toBeGreaterThan(0);await expect(reader.locator('#next')).toBeEnabled();await reader.locator('#next').click();await expect(reader.locator('#page')).toHaveValue('2',{timeout:15000});
 await math.locator('[data-education-page="study/curriculum"]').click();await expect(page.locator('#educationHeaderTabs')).toBeHidden();await expect(page.locator('#content .learning-section-tabs')).toHaveCount(0);await page.screenshot({path:'test-results/education-grid-modern.png'});await page.setViewportSize({width:390,height:844});await page.locator('#menu').click();await expect(page.locator('#sidebar #personaSwitcher')).toBeVisible();await math.locator('[data-education-page="learning"]').click();await expect(page.locator('.guide-hero')).toBeVisible();  await page.locator('.education-workspace-toolbar [data-chapter-notes]').click();await expect(page.locator('#chapterNotesDrawer')).toBeVisible();await page.locator('[data-close-notes]').last().click();await page.keyboard.press('Escape');await expect(page.locator('#chapterWorkspace')).toBeHidden();await page.locator('#menu').click();await page.locator('#nav').evaluate(el=>el.scrollTop=0);await page.locator('#personaSwitcher').click();await page.locator('[data-persona="p3"]').click();await expect(page.locator('#personaName')).toContainText('Sasha');await expect(page.locator('#chapterNotesDrawer')).toBeHidden();await page.screenshot({path:'test-results/education-grid-mobile.png'});expect(errors).toEqual([]);
});
