const {test,expect}=require('@playwright/test');
test('class subject chapter tree switches learners and retains top section tabs',async({page})=>{
  await page.goto('http://127.0.0.1:8765/#/study/curriculum');
  await page.evaluate(()=>localStorage.clear());await page.reload();
  await expect(page.locator('.education-class > summary')).toHaveCount(2);
  await expect(page.locator('.education-class').first()).toContainText('Class 12');
  await expect(page.locator('.education-class').last()).toContainText('Class 7');
  expect(await page.locator('#educationHeaderTabs .learning-section-tabs button').allTextContents()).toEqual(['Overview','Curriculum','Planner','Progress']);
  const class7=page.locator('.education-class').last();
  const math=class7.locator('.education-subject').filter({has:page.locator('summary').filter({hasText:/^Mathematics/})});
  await math.locator('summary').click();
  const chapter=math.locator('[data-education-chapter]').first();
  const title=await chapter.locator('b').innerText();
  await chapter.click();
  await expect(page.locator('#chapterWorkspace')).toBeVisible();
  await expect(page.locator('#chapterWorkspaceBody')).toContainText(title);
  await expect(page.locator('#personaName')).toContainText('Ishaan');
  await expect(page.locator('#educationLearner')).toHaveValue('p4');
  await expect(page.locator('#nav .education-class')).toHaveCount(2);
  await page.locator('#educationHeaderTabs [data-route="study/planner"]').click();
  await expect(page).toHaveURL(/study\/planner/);
  await expect(page.locator('#chapterWorkspace')).toBeHidden();
  await expect(page.locator('#educationLearner')).toHaveValue('p4');
  await page.locator('.learning-section-tabs [data-route="study/curriculum"]').click();
  await page.screenshot({path:'test-results/education-tree-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(async()=>Math.round((await page.locator('.app-shell').boundingBox()).x)).toBe(0);
  await expect(page.locator('#content .learning-section-tabs')).toBeVisible();
  await page.screenshot({path:'test-results/education-tree-mobile.png'});
  await page.setViewportSize({width:1280,height:720});
  const firstChapter=page.locator('.education-class').last().locator('.education-subject').filter({has:page.locator('summary').filter({hasText:/^Mathematics/})});
  await firstChapter.locator('summary').click();
  await firstChapter.locator('[data-education-chapter]').first().click();
  await page.locator('#navigationGroup').selectOption('household');
  await expect(page.locator('#chapterWorkspace')).toBeHidden();
  await expect(page).toHaveURL(/global\/overview/);
});
