const {test,expect}=require('@playwright/test');
test('level tracking lives in Progress and overview is read only',async({page})=>{
 await page.goto('http://127.0.0.1:8765/#/study/curriculum');await page.evaluate(()=>localStorage.clear());await page.reload();
 const math=page.locator('.education-class').last().locator('.education-subject').filter({has:page.locator('summary').filter({hasText:/^Mathematics/})});await math.locator('summary').click();
 await expect(page.locator('.chapter-progress-overview')).toBeVisible();await expect(page.locator('.chapter-progress-overview select')).toHaveCount(0);
 await page.locator('#educationHeaderTabs [data-route="study/curriculum"]').click();
 expect(await page.locator('#educationHeaderTabs button').allTextContents()).toEqual(['Overview','Progress','Planner','Study Guide','Genius Mind','Formulae / Key ideas','Read Book','My Notes','Practice & Tests','Assignments']);
 await expect(page.locator('#breadcrumb')).toHaveCount(0);await expect(page.locator('[data-study-today],.study-open')).toHaveCount(0);
 const chapter=page.locator('.progress-chapter').first();await chapter.locator('summary').click();const id=await chapter.locator('[data-study-level]').first().getAttribute('data-lesson');
 await page.evaluate(id=>{HM.data.state.settings.chapterMastery ||= {};HM.data.state.settings.chapterMastery.p4 ||= {};HM.data.state.settings.chapterMastery.p4[id]=42;HM.data.save();},id);await chapter.locator('[data-study-level="learning"]').selectOption('60');await chapter.locator('[data-study-level="revision"]').selectOption('30');await chapter.locator('[data-study-level="expert"]').selectOption('10');await expect(chapter).toHaveAttribute('open','');
 await chapter.locator('[data-subchapter-progress]').first().click();await expect(chapter).toHaveAttribute('open','');await chapter.locator('[name="nextStep"]').fill('Revise place value');await chapter.locator('[type="submit"]').click();
 const saved=await page.evaluate(id=>HM.data.state.settings.chapterDaily.p4[id],id);expect(saved.levels).toEqual({learning:60,revision:30,expert:10});expect(saved.nextStep).toBe('Revise place value');expect(await page.evaluate(id=>HM.data.state.settings.chapterMastery.p4[id],id)).toBe(42);expect(await page.evaluate(()=>HM.data.state.settings.chapterDaily.p3 || {})).toEqual({});
 await page.screenshot({path:'test-results/level-progress-desktop.png'});await page.reload();await page.locator('.progress-chapter').first().locator('summary').click();await expect(page.locator('[data-study-level="learning"]').first()).toHaveValue('60');
 await page.locator('#educationHeaderTabs [data-route="study/overview"]').click();await expect(page.locator('.chapter-overview-row').first()).toContainText('33% overall');
 await page.locator('#educationHeaderTabs [data-study-section="understand"]').click();await expect(page.locator('#chapterWorkspace')).toBeVisible();await expect(page.locator('#chapterWorkspace .daily-progress-panel')).toHaveCount(0);await expect(page.locator('.chapter-content-tabs')).toHaveCount(0);await expect(page.locator('.chapter-support-rail')).toBeVisible();
 await page.locator('#educationHeaderTabs [data-route="study/curriculum"]').click();await page.setViewportSize({width:390,height:844});await page.locator('.progress-chapter').first().locator('summary').click();await expect(page.locator('[data-study-level="expert"]').first()).toBeVisible();await page.screenshot({path:'test-results/level-progress-mobile.png'});
});
