const {test,expect}=require('@playwright/test');
test('choose a level first then drag chapter percentages without losing focus or saved records',async({page})=>{
 await page.goto('http://127.0.0.1:8765/#/study/curriculum');await page.evaluate(()=>localStorage.clear());await page.reload();
 const math=page.locator('.education-class').last().locator('.education-subject').filter({has:page.locator('summary').filter({hasText:/^Mathematics/})});await math.locator('summary').click();await page.locator('#educationHeaderTabs [data-route="study/curriculum"]').click();
 await expect(page.locator('.progress-choose-prompt')).toBeVisible();await expect(page.getByRole('slider')).toHaveCount(0);
 await page.locator('[data-progress-level="learning"]').click();await expect(page.getByRole('slider')).toHaveCount(15);await expect(page.locator('[data-progress-level="learning"]')).toHaveAttribute('aria-pressed','true');
 const slider=page.getByRole('slider').first(),id=await slider.getAttribute('data-lesson');
 await page.evaluate(id=>{HM.data.state.settings.chapterMastery ||= {};HM.data.state.settings.chapterMastery.p4 ||= {};HM.data.state.settings.chapterMastery.p4[id]=42;HM.data.save();},id);
 await slider.focus();await slider.press('Home');const box=await slider.boundingBox();await page.mouse.move(box.x+12,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+12+(box.width-24)*.6,box.y+box.height/2,{steps:12});await expect(slider).toHaveValue('60');await expect(page.locator('.progress-range-value').first()).toContainText('60');await page.mouse.up();await expect(page.locator('.progress-save-status')).toHaveText('Saved');
 await page.locator('[data-progress-level="revision"]').click();await expect(slider).toHaveValue('0');await slider.focus();await slider.press('Home');await slider.press('ArrowRight');await slider.press('ArrowRight');await slider.press('ArrowRight');await expect(slider).toBeFocused();await expect(slider).toHaveValue('30');
 await page.locator('[data-progress-level="expert"]').click();await slider.focus();await slider.press('Home');await slider.press('ArrowRight');await expect(slider).toHaveValue('10');
 await page.locator('.progress-chapter').first().locator('summary').click();await page.locator('.progress-chapter').first().locator('[data-subchapter-progress]').first().click();await expect(page.locator('.progress-chapter').first()).toHaveAttribute('open','');
 const saved=await page.evaluate(id=>HM.data.state.settings.chapterDaily.p4[id],id);expect(saved.levels).toEqual({learning:60,revision:30,expert:10});expect(await page.evaluate(id=>HM.data.state.settings.chapterMastery.p4[id],id)).toBe(42);expect(await page.evaluate(()=>HM.data.state.settings.chapterDaily.p3 || {})).toEqual({});
 await page.locator('.progress-chapter').first().locator('summary').click();await page.locator('.progress-workbench').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/progress-sliders-desktop.png'});
 await page.reload();await expect(page.locator('[data-progress-level="expert"]')).toHaveAttribute('aria-pressed','true');await expect(slider).toHaveValue('10');await page.locator('[data-progress-level="learning"]').click();await expect(slider).toHaveValue('60');
 await page.locator('#educationHeaderTabs [data-route="study/overview"]').click();await expect(page.locator('.chapter-overview-row').first()).toContainText('33% overall');await expect(page.locator('.chapter-progress-overview input')).toHaveCount(0);
 await page.locator('#educationHeaderTabs [data-route="study/curriculum"]').click();await page.setViewportSize({width:390,height:844});await expect.poll(async()=>Math.round((await page.locator('.app-shell').boundingBox()).x)).toBe(0);await slider.scrollIntoViewIfNeeded();await expect(slider).toBeVisible();await page.screenshot({path:'test-results/progress-sliders-mobile.png'});
});
